version: '3.8'

services:
  react-frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    networks:
      - users-network

  backend:
    build:
      context: ./UserAuthentication
    ports:
      - "5223:8080"
    environment:
      - ConnectionStrings__UserDatabase=Server=sqlserver;Database=UserDb;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    networks:
      - users-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - users-network

volumes:
  sqlserverdata:

networks:
  users-network:
    driver: bridge
