// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserAuthentication.Data;

#nullable disable

namespace UserAuthentication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserAuthentication.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            PasswordHash = "AQAAAAIAAYagAAAAEH9MUVqZAd1HJosVdpILz2HzVbafsV1UNW7uBb6ZlquyAnoT7hV9y/FtkldxdkhgzQ==",
                            Role = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            PasswordHash = "AQAAAAIAAYagAAAAEEGKNzLpcJjG40N9LOWG+6BZg8mHNvR6XLtut5Vm8AQRx4y7NnVw05rT193He3UwGw==",
                            Role = 0,
                            Username = "user1"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            PasswordHash = "AQAAAAIAAYagAAAAEFHBUMJsZL1Jj+wR8Szfr/fDa51V4XTp2xANQslpxsicfFHWvlxXB+E0oxaxDUmE3g==",
                            Role = 0,
                            Username = "user2"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            PasswordHash = "AQAAAAIAAYagAAAAENfqHUq9MwyEP9BAY9x+rvumK8ZR4b07d5SXCkutS69KPo2F8NGjzrPrAOUYxd66Qw==",
                            Role = 0,
                            Username = "user3"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            PasswordHash = "AQAAAAIAAYagAAAAEPGaYIJS4Uhqg0Sb31S+g932GOvjKPZrdQvtQmGeNzfsGdWgAnI/7DQ9iKtqW2Xwdw==",
                            Role = 0,
                            Username = "user4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
